theme: jekyll-theme-minimal
google_analytics: UA-148711615-2

logo: images/profile.png
title: Scott's Portfolio
description:
  G'day! I'm Scott, a developer with a love for building awesome apps.<br>
  <br>
  <strong>I'm currently in search of new opportunies.</strong> If you're in need of a Full Stack Developer then don't be a stranger!<br>
  <br>
  Enjoy my portfolio!
github: https://github.com/kangabru
linkedin: https://www.linkedin.com/in/scott-gibbs-52065380/
