theme: jekyll-theme-minimal
google_analytics: UA-148711615-2

logo: images/profile.png
title: Scott's Portfolio
github: https://github.com/kangabru
linkedin: https://www.linkedin.com/in/scott-gibbs-52065380/
