logo: "https://raw.githubusercontent.com/kangabru/kangabru.github.io/master/images/logo.png"
description: > # newlines will be ignored in this theme, using <br> instead
  <br>
  Kangabru Portfolio
  <br><br>
  Something something something<br>
  // Some stuff<br>
  // More stuff<br>
  // Even more stuff<br>
  <br><br>
  <a href="https://www.linkedin.com/in//">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-123