theme: jekyll-theme-minimal
# google_analytics: UA-123

logo: images/logo.png
title: Kangabru Portfolio
description:
  Something something something<br>
  - Some stuff<br>
  - More stuff<br>
  - Even more stuff<br>
  <br>
  <a href="https://www.linkedin.com/in//">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com//">View My Github Profile</a>
